In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
type(a)

numpy.ndarray

In [4]:
a[0]

1

In [5]:
a.ndim

1

In [6]:
a.shape

(4,)

In [14]:
b=np.array([[1,2,3],[2,3,4]])
b.size

6

In [33]:
b[1:,:2]

array([[2, 3]])

In [35]:
c=np.arange(10,80,10)
c

array([10, 20, 30, 40, 50, 60, 70])

In [37]:
d=[1,2,-3]
y=c[d]
y

array([20, 30, 50])

In [38]:
c[d]=90
c

array([10, 90, 90, 40, 90, 60, 70])

In [41]:
t=(c==c[d])
t

C:\Users\DELL\AppData\Local\Temp/ipykernel_7784/927441143.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  t=(c==c[d])


False

In [47]:
C=np.array([5,6,8,7])
a+C

array([ 6,  8, 11, 11])

In [48]:
c.sum()

26

In [49]:
b.sum(axis=0)

array([3, 5, 7])

In [50]:
b.sum(axis=1)

array([6, 9])

In [51]:
b.min()

1

In [52]:
a.max()

4

In [53]:
#return index position min is 0 and max is 3
a.argmin()

0

In [54]:
a.argmax()

3

In [56]:
#Max position minus Min position
a.ptp()

3

In [57]:
c.mean()

6.5

In [58]:
c.std()

1.118033988749895

In [59]:
c.var()

1.25

In [60]:
a.any()

True

In [61]:
a.all()

True

In [62]:
a==a.max()

array([False, False, False,  True])

In [63]:
np.where(a==a.max())

(array([3], dtype=int64),)

In [68]:
np.where(a>0)

(array([0, 1, 2, 3], dtype=int64),)

In [69]:
b.flatten()

array([1, 2, 3, 2, 3, 4])

In [71]:
b

array([[1, 2, 3],
       [2, 3, 4]])

In [70]:
#Flatten does not change the actual array
b[0]

array([1, 2, 3])